Camera Scan Component (fixes #2)
surfacers/what-ae-brick pull request #10
Opened 2021-05-02 06:30 UTC by bemayr

[WIP]

2021-05-02 07:04 UTC, danielxbauer requested changes
Good work! I have some small changes/questions added.

2021-05-02 07:04 UTC, danielxbauer commented on navigation/BottomTabNavigator.tsx
> +        options={{ headerTitle: 'What Æ brick?' }}
Can you remove the header completly to have a bigger camera?

2021-05-02 07:04 UTC, danielxbauer commented on screens/ScanScreen.tsx
>  export default function HistoryScreen() {
Isnt that the "ScanScreen"?

2021-05-02 07:04 UTC, danielxbauer commented on screens/ScanScreen.tsx
> +    return <View />;
When does null happen here?

2021-05-03 05:37 UTC, bemayr commented on navigation/BottomTabNavigator.tsx
> +        options={{ headerTitle: 'What Æ brick?' }}
Was thinking of this (and tried it) and decided against it because we (1) don't need the space and (2) it really doesn't look that good 😅

2021-05-25 11:37 UTC, danielxbauer approved these changes

2021-05-25 11:38 UTC, merged